  main.cpp
C:\Users\sssr2\source\repos\CPython\CPython.h(29,18): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(29,18): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(27,37): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::pair<_Ty1,_Ty2>(void)"
C:\Users\sssr2\source\repos\CPython\CPython.h(29,38): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(29,38): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(27,37): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::pair<_Ty1,_Ty2>(void)"
C:\Users\sssr2\source\repos\CPython\CPython.h(36,17): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(36,17): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(32,37): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::map<T1,T2,std::less<_Ty>,std::allocator<std::pair<const _Kty,_Ty>>>(void)"
C:\Users\sssr2\source\repos\CPython\CPython.h(36,34): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(36,34): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(32,37): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::map<T1,T2,std::less<_Ty>,std::allocator<std::pair<const _Kty,_Ty>>>(void)"
C:\Users\sssr2\source\repos\CPython\CPython.h(41,17): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(41,17): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(32,37): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::map<T1,T2,std::less<_Ty>,std::allocator<std::pair<const _Kty,_Ty>>>(void)"
C:\Users\sssr2\source\repos\CPython\CPython.h(41,34): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(41,34): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(32,37): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::map<T1,T2,std::less<_Ty>,std::allocator<std::pair<const _Kty,_Ty>>>(void)"
C:\Users\sssr2\source\repos\CPython\CPython.h(49,17): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(49,17): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(46,37): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::unordered_map<T1,T2,std::hash<_Kty>,std::equal_to<_Ty>,std::allocator<std::pair<const _Kty,_Ty>>>(void)"
C:\Users\sssr2\source\repos\CPython\CPython.h(49,34): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(49,34): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(46,37): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::unordered_map<T1,T2,std::hash<_Kty>,std::equal_to<_Ty>,std::allocator<std::pair<const _Kty,_Ty>>>(void)"
C:\Users\sssr2\source\repos\CPython\CPython.h(54,17): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(54,17): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(46,37): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::unordered_map<T1,T2,std::hash<_Kty>,std::equal_to<_Ty>,std::allocator<std::pair<const _Kty,_Ty>>>(void)"
C:\Users\sssr2\source\repos\CPython\CPython.h(54,34): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(54,34): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(46,37): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::unordered_map<T1,T2,std::hash<_Kty>,std::equal_to<_Ty>,std::allocator<std::pair<const _Kty,_Ty>>>(void)"
C:\Users\sssr2\source\repos\CPython\CPython.h(61,62): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(61,62): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(59,33): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::array<_Ty,_Size>(void)"
C:\Users\sssr2\source\repos\CPython\CPython.h(62,55): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(62,55): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(59,33): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::array<_Ty,_Size>(void)"
C:\Users\sssr2\source\repos\CPython\CPython.h(79,55): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(79,55): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(66,23): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::vector<T,std::allocator<_Ty>>(void)"
C:\Users\sssr2\source\repos\CPython\CPython.h(96,55): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(96,55): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(83,23): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::list<T,std::allocator<_Ty>>(void)"
C:\Users\sssr2\source\repos\CPython\CPython.h(113,56): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(113,56): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(100,23): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::forward_list<T,std::allocator<_Ty>>(void)"
C:\Users\sssr2\source\repos\CPython\CPython.h(130,52): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(130,52): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(117,23): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::set<T,std::less<_Ty>,std::allocator<_Ty>>(void)"
C:\Users\sssr2\source\repos\CPython\CPython.h(147,52): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(147,52): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(134,23): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::multiset<T,std::less<_Ty>,std::allocator<_Ty>>(void)"
C:\Users\sssr2\source\repos\CPython\CPython.h(164,52): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(164,52): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(151,23): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::unordered_set<T,std::hash<_Kty>,std::equal_to<_Ty>,std::allocator<_Ty>>(void)"
C:\Users\sssr2\source\repos\CPython\CPython.h(181,52): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(181,52): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(168,23): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::unordered_multiset<T,std::hash<_Kty>,std::equal_to<_Ty>,std::allocator<_Ty>>(void)"
C:\Users\sssr2\source\repos\CPython\CPython.h(198,50): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(198,50): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(185,23): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::queue<T,std::deque<T,std::allocator<_Ty>>>(void)"
C:\Users\sssr2\source\repos\CPython\CPython.h(215,50): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(215,50): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(202,23): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::priority_queue<T,std::vector<T,std::allocator<_Ty>>,std::less<vector<T,std::allocator<_Ty>>::value_type>>(void)"
C:\Users\sssr2\source\repos\CPython\CPython.h(232,55): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(232,55): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(219,23): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::deque<T,std::allocator<_Ty>>(void)"
C:\Users\sssr2\source\repos\CPython\CPython.h(249,50): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\CPython.h(283,1): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
C:\Users\sssr2\source\repos\CPython\CPython.h(249,50): message : "Input": объявление функции должно быть доступно, так как ни один из аргументов не зависит от параметра шаблона
C:\Users\sssr2\source\repos\CPython\CPython.h(236,23): message : Сообщение диагностики возникло в созданной компилятором функции "Input::operator std::stack<T,std::deque<T,std::allocator<_Ty>>>(void)"
C:\Users\sssr2\source\repos\CPython\main.cpp(7,16): error C2512: Input: нет подходящего конструктора по умолчанию
C:\Users\sssr2\source\repos\CPython\main.cpp(7,16): message : Ни один конструктор не смог принять исходный тип, либо разрешение перегрузки конструктора неоднозначно
